"""General utilities and constants."""
# Constants
NUM_TEAMS = 32
NUM_WEEKS_PER_SEASON = 17
NUM_GAMES_PER_TEAM = 16
NUM_REGULAR_SEASON_GAMES = NUM_TEAMS * NUM_GAMES_PER_TEAM / 2
NUM_PLAYOFF_TEAMS = 12
NUM_PLAYOFF_GAMES = NUM_PLAYOFF_TEAMS - 1
NUM_TOTAL_GAMES = NUM_REGULAR_SEASON_GAMES + NUM_PLAYOFF_GAMES
